name: Mein erster Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: Hallo Welt ausführen
        run: echo "Hallo GitHub Actions, das ist mein erster Workflow!"
